# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name']},
        ),
        migrations.AddField(
            model_name='image',
            name='photo_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
