# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_image', models.ImageField(upload_to='travel/')),
                ('family_image', models.ImageField(upload_to='family/')),
                ('old_image', models.ImageField(upload_to='old/')),
                ('download_image', models.ImageField(upload_to='download/')),
                ('screenshot_image', models.ImageField(upload_to='screenshot/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogallery.Image')),
                ('tags', models.ManyToManyField(to='photogallery.tags')),
            ],
        ),
    ]
