# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0004_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['photo_image']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='download_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='family_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='old_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='screenshot_image',
        ),
    ]
